### ISSUE TITLE
UCI Options seems not working

### ISSUE THREAD

**Issue by PikaCat-OuO** [Disservin/fast#4]
Setting UCI options in the "Engine" page seems to have no effect.

Presumably the issue happens here:
https://github.com/Disservin/fast/blob/6d7bef93848f3b03cdf7fbfd932fddb0e31892a0/src/ts/ChessProcess.ts#L62-L64

Suggested fix:
remove `async () =>`, like https://github.com/official-pikafish/fast/blob/c7fb21b329100e86eec6fba0726186bd2cf39ed3/src/ts/ChessProcess.ts#L62-L64

**Comment by Disservin** [comment]
ty!
